"""Generate clients/unde/mapping.yaml from the MR + March taxonomi.

One-off authoring aid. The MR carries revenue per market by cost-center
code (R001..R009 etc.) and the taxonomi renamed several services, so the
service<->code correspondence was decoded by value-matching the March
column (see clients/unde/MR_LAYOUT.md). Re-run only if the taxonomi or MR
layout changes; the emitted mapping.yaml is the tracked artefact.
"""
from __future__ import annotations

from pathlib import Path

from openpyxl import load_workbook

CLIENT = Path(__file__).resolve().parents[1]
MR = CLIENT / "raw/04/Undelucram - Monthly reports 2026.xlsx"
TAX = CLIENT / "raw/taxonomi_act_2026-03.xlsx"

# market -> cost-center letter (Sales section)
LETTER = {
    "Romania": "R", "Greece": "G", "Hungary": "H", "Moldova": "M",
    "Bulgaria": "B", "Czech Republic": "C", "MENA": "X", "Poland": "P",
    "Other markets": "O",
}
# taxonomi service -> cost-center suffix (Sales). None = no MR source yet.
SUFFIX = {
    "Employer branding": "001",
    "Jobbing": "002",
    "Industry Benchmarking Tool (Basic)": "003",     # MR label "Salary report"
    "Industry Benchmarking Tool (Enterprise)": "004",  # MR label "Brand perception"
    "Advertising": "005",
    "Linkedin Learning": "009",
    "HR Vendor Marketplace": None,
    "Integration with InterviewsUp": None,
}

# Expense rows keyed by cost-center code in MR col C.
CC_EXPENSE = {
    ("Cost of Sales", "Payroll CoS", "Payroll CoS"): "A018",
    ("Cost of Sales", "Infrastructure", "Infrastructure"): "A019",
    ("Cost of Sales", "Software & Tools", "Software & Tools"): "A020",
    ("Cost of Sales", "LinkedIn Learning (share)", "LinkedIn Learning (share)"): "A021",  # MR "Other CoS" (best-guess)
    ("R&D", "Payroll R&D", "Payroll R&D"): "A011",
    ("R&D", "Software & Tools", "Software & Tools"): "A012",
    ("R&D", "Certifications/Patents/Other", "Certifications/Patents/Other"): "A013",
    ("S&M", "Other marketing expense", "Other marketing expense"): "A001",
    ("S&M", "Software & Tools", "Software & Tools"): "A002",
    ("G&A", "Payroll G&A", "Payroll G&A"): "A003",
    ("G&A", "Office & Utilities", "Office & Utilities"): "A004",
    ("G&A", "Infrastructure, tools & equipment", "Infrastructure, tools & equipment"): "A005",
    ("G&A", "Software & Tools", "Software & Tools"): "A006",
    ("G&A", "Legal and Professional", "Legal and Professional"): "A007",
    ("G&A", "Team Building costs", "Team Building costs"): "A008",
    ("G&A", "Travel", "Travel"): "A009",
    ("G&A", "Miscellaneous expenses", "Miscellaneous expenses"): "A010",
    ("Finance income", "Finance income", "Finance income"): "A023",
    ("Finance costs", "Finance costs", "Finance costs"): "A024",
    ("Depreciation and amortization", "Depreciation and amortization",
     "Depreciation and amortization"): "A014",
}
# S&M market sub-rows: grp -> (first_row, last_row) range in MR IS to label-search.
SM_RANGE = {"Payroll S&M": (74, 83), "Marketing": (85, 93), "Events": (95, 103)}
IS_NULL = {  # taxonomi keys with no MR source
    ("Other non operational revenues",) * 1,
}


def q(s):
    return '"' + str(s).replace('"', '\\"') + '"'


def main():
    mrwb = load_workbook(MR, data_only=True)
    is_ws = mrwb["Income Statement"]
    cf_ws = mrwb["Cash Flow Statement"]
    bs_ws = mrwb["Balance Sheet"]
    txwb = load_workbook(TAX, data_only=True)

    # MR IS: index by cost-center code (col C) and label (col B).
    cc_to_row, isB = {}, {}
    for r in range(1, is_ws.max_row + 1):
        b = is_ws.cell(r, 2).value
        c = is_ws.cell(r, 3).value
        if b is not None:
            isB[r] = b
        if isinstance(c, str) and c.strip():
            cc_to_row[c.strip()] = r

    def label_in_range(lo, hi, target):
        for r in range(lo, hi + 1):
            v = is_ws.cell(r, 2).value
            if isinstance(v, str) and v.strip() == target:
                return r, v
        return None, None

    out = []
    out.append("# MR -> Taxonomi mapping for Undelucram. Auto-generated by")
    out.append("# one_offs/gen_mapping.py, then reviewed. Source layout in MR_LAYOUT.md.")
    out.append("#")
    out.append("# mr_row is 1-indexed; mr_label is the EXACT MR label (incl. trailing")
    out.append("# whitespace) used for the loader's label-vs-row fallback. mr_row: null")
    out.append("# = no MR source (derived KPI or no line yet).")
    out.append("")
    out.append("mr_layout:")
    out.append("  IS: { sheet: \"Income Statement\",   header_row: 2, label_col: 2, period_format: month_name }")
    out.append("  CF: { sheet: \"Cash Flow Statement\", header_row: 2, label_col: 1, period_format: month_name }")
    out.append("  BS: { sheet: \"Balance Sheet\",       header_row: 2, label_col: 1, period_format: month_name }")
    out.append("")

    # ---- IS ----
    out.append("mapping_is:")
    txis = txwb["IS (Actual)"]

    def emit(mr_row, mr_label, data, grp, sub, note=""):
        rowstr = "null" if mr_row is None else str(mr_row)
        lbl = "null" if mr_label is None else q(mr_label)
        line = (f"  - {{ mr_row: {rowstr}, mr_label: {lbl}, "
                f"data: {q(data)}, grp: {q(grp)}, subgroup: {q(sub)} }}")
        if note:
            line += f"  # {note}"
        out.append(line)

    for r in range(2, txis.max_row + 1):
        data = txis.cell(r, 1).value
        grp = txis.cell(r, 2).value
        sub = txis.cell(r, 3).value
        if data is None:
            continue
        if data == "MRR":
            # Taxonomi MRR is the MRR-classified revenue from the MRR Schedule
            # (workstream B), NOT the management report's "MRR" row (= total
            # Sales). No MR source -> filled in the MRR-schedule step.
            emit(None, None, data, grp, sub, "sourced from MRR Schedule, not MR")
        elif data == "Sales":
            suf = SUFFIX.get(sub)
            letter = LETTER.get(grp)
            cc = (letter + suf) if (suf and letter) else None
            mr_row = cc_to_row.get(cc)
            if mr_row:
                emit(mr_row, isB.get(mr_row), data, grp, sub)
            else:
                emit(None, None, data, grp, sub, "no MR source for this market/service")
        elif grp in SM_RANGE:  # S&M market sub-rows
            if sub == "Sales Commissions":
                mr_row, lbl = label_in_range(70, 84, "Sales Commissions")
            else:
                lo, hi = SM_RANGE[grp]
                mr_row, lbl = label_in_range(lo, hi, sub)
            emit(mr_row, lbl, data, grp, sub)
        elif (data, grp, sub) in CC_EXPENSE:
            cc = CC_EXPENSE[(data, grp, sub)]
            mr_row = cc_to_row[cc]
            emit(mr_row, isB.get(mr_row), data, grp, sub, f"CC {cc}")
        else:  # Other non operational revenues, Income tax -> no MR source
            emit(None, None, data, grp, sub, "no MR source")

    # ---- CF ----
    out.append("")
    out.append("mapping_cf:")
    txcf = txwb["CF Indirect (Actual)"]
    # taxonomi CF row -> MR CF row (label col A). null = derived/no source.
    CF_MAP = {
        2: 5, 3: 6, 4: 7, 5: 8, 6: 9, 7: 10, 8: 11, 9: 12, 10: 13, 11: 14,
        12: 15, 13: 17, 14: 18, 15: None, 16: 20, 17: 21, 18: 22,
        19: 25,   # financing "Other ..." value-matches MR "Other (interest)"
        20: 24, 21: None,
        22: 29,   # Beginning Cash Balance
        23: None,  # % Change in cash (derived; engine has no formula -> flagged)
        24: 19,   # Capex = MR "Cash Flow from Investing Activities" total
        25: None,  # Gross Fixed assets -> kpi_derivations (sum of BS fixed assets)
    }
    for r in range(2, txcf.max_row + 1):
        data = txcf.cell(r, 1).value
        grp = txcf.cell(r, 2).value
        sub = txcf.cell(r, 3).value
        if data is None:
            continue
        mr_row = CF_MAP.get(r)
        lbl = cf_ws.cell(mr_row, 1).value if mr_row else None
        rowstr = "null" if mr_row is None else str(mr_row)
        lblstr = "null" if lbl is None else q(lbl)
        out.append(f"  - {{ mr_row: {rowstr}, mr_label: {lblstr}, "
                   f"data: {q(data)}, grp: {q(grp)}, subgroup: {q(sub)} }}")

    # ---- BS ----
    out.append("")
    out.append("mapping_bs:")
    txbs = txwb["BS (Actual)"]
    BS_MAP = {
        2: 7, 3: 8, 4: 10, 5: 11, 6: 15, 7: 16, 8: 17, 9: 13, 10: 14,
        11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 28, 17: 32, 18: 33,
        19: 34, 20: 35, 21: 31,
        22: None, 23: None, 24: None,  # turnovers + WC -> kpi_derivations
    }
    for r in range(2, txbs.max_row + 1):
        data = txbs.cell(r, 1).value
        grp = txbs.cell(r, 2).value
        sub = txbs.cell(r, 3).value
        if data is None:
            continue
        mr_row = BS_MAP.get(r)
        lbl = bs_ws.cell(mr_row, 1).value if mr_row else None
        rowstr = "null" if mr_row is None else str(mr_row)
        lblstr = "null" if lbl is None else q(lbl)
        out.append(f"  - {{ mr_row: {rowstr}, mr_label: {lblstr}, "
                   f"data: {q(data)}, grp: {q(grp)}, subgroup: {q(sub)} }}")

    # ---- derived KPIs ----
    out.append("")
    out.append(KPI_BLOCK)
    out.append(KNOWN_DISCREPANCIES)

    (CLIENT / "mapping.yaml").write_text("\n".join(out) + "\n")
    print("wrote", CLIENT / "mapping.yaml")
    mrwb.close()
    txwb.close()


KPI_BLOCK = """kpi_derivations:
  # Working Capital = current assets - current liabilities (reproduces Mar 68,081.8).
  - statement_for_target: BS
    target: ["Working Capital", "Working Capital", "Working Capital"]
    formula: working_capital
    store_as: float
    current_assets:
      - { statement: BS, key: ["Current assets", "Other receivables", "Other receivables"] }
      - { statement: BS, key: ["Current assets", "Tax receivable", "Tax receivable"] }
      - { statement: BS, key: ["Current assets", "Pre-paid expenses", "Pre-paid expenses"] }
      - { statement: BS, key: ["Cash and cash equivalents", "Cash and cash equivalents", "Cash and cash equivalents"] }
      - { statement: BS, key: ["Trade receivables", "Trade receivables", "Trade receivables"] }
    current_liabilities:
      - { statement: BS, key: ["Current Liabilities", "Payables to personnel", "Payables to personnel"] }
      - { statement: BS, key: ["Current Liabilities", "Deferred revenue", "Deferred revenue"] }
      - { statement: BS, key: ["Current Liabilities", "Tax payable", "Tax payable"] }
      - { statement: BS, key: ["Current Liabilities", "Other payables", "Other payables"] }
      - { statement: BS, key: ["Trade payables", "Trade payables", "Trade payables"] }

  # Gross Fixed assets = sum of BS fixed-asset rows (reproduces Mar 198,195.3).
  - statement_for_target: CF
    target: ["Gross Fixed assets", "Gross Fixed assets", "Gross Fixed assets"]
    formula: sum
    store_as: float
    sources:
      - { statement: BS, key: ["Non-current assets", "Non-tangible fixed assets", "Trademark & Patents"] }
      - { statement: BS, key: ["Non-current assets", "Non-tangible fixed assets", "Research and Development Asset"] }
      - { statement: BS, key: ["Non-current assets", "Tangible fixed assets", "Property, plant and equipment"] }
      - { statement: BS, key: ["Non-current assets", "Tangible fixed assets", "Fixtures and fittings"] }

  # Account receivable turnover = Sales / avg(Trade receivables).
  - statement_for_target: BS
    target: ["Account receivable turnover", "Account receivable turnover", "Account receivable turnover"]
    formula: turnover_ratio
    store_as: float
    numerator: { type: data_aggregate, source: IS, data: "Sales" }
    avg_balance_key: { statement: BS, key: ["Trade receivables", "Trade receivables", "Trade receivables"] }

  # Accounts payable turnover = (opex - personnel) / avg(Trade payables).
  - statement_for_target: BS
    target: ["Accounts payable turnover", "Accounts payable turnover", "Accounts payable turnover"]
    formula: ap_turnover
    store_as: float
    cost_data_classes: ["Cost of Sales", "S&M", "G&A", "R&D"]
    personnel_keys:
      - ["Cost of Sales", "Payroll CoS", "Payroll CoS"]
      - ["R&D", "Payroll R&D", "Payroll R&D"]
      - ["G&A", "Payroll G&A", "Payroll G&A"]
    avg_balance_key: { statement: BS, key: ["Trade payables", "Trade payables", "Trade payables"] }
"""

KNOWN_DISCREPANCIES = """
# Rows that intentionally do NOT reconcile to the management report — do not
# re-investigate each month unless the underlying source changes.
known_discrepancies:
  - statement: IS
    taxonomi_key: ["MRR", "MRR", "MRR"]
    reason: |
      Taxonomi MRR is the MRR-classified revenue produced in the MRR Schedule
      (workstream B), e.g. Mar 2026 = EUR 106,353. The management report's own
      "MRR" row is total Sales (Mar EUR 108,417). Left null here; populated in
      the MRR-schedule step.
  - statement: BS
    taxonomi_key: ["Accounts payable turnover", "Accounts payable turnover", "Accounts payable turnover"]
    reason: |
      Derived KPI; our ap_turnover basis (CoS+S&M+G&A+R&D less the three main
      payroll lines, over avg trade payables) gives ~0.7 vs the client's 0.4.
      The client's exact opex/personnel basis is unconfirmed. Best-effort only.
  - statement: CF
    taxonomi_key: ["LinkedIn Learning (share)", null, null]
    reason: |
      Cost of Sales | "LinkedIn Learning (share)" is mapped to MR "Other CoS"
      (A021) as a best guess (zero in Mar; EUR 14,771 in Apr). Confirm the
      correct destination with the client's chart of accounts.
"""

if __name__ == "__main__":
    main()
